### PR TITLE
Added `Aura.Mabi.Structs` to Compiler usings.

### PR DESCRIPTION
**Pull request by ImaBrokeDude**
I added this in the event that someone wanted to modify or manipulate stat related things inside a GM command.

(Stat Regens, Stat Mods, etc.)

### CODE REVIEW

**Comment by exectails** [comment]
What do the structs have to do with regens and mods?

**Comment by ImaBrokeDude** [comment]
`StatRegens.Add()` requires `Aura.Mabi.Structs.Stat` as one of it's arguments.

`target.Regens.Add("godmode", Stat.Life, 1000f, target.LifeMax);`

**Comment by exectails** [comment]
There is no `Aura.Mabi.Structs.Stat`.

**Comment by ImaBrokeDude** [comment]
> There is no `Aura.Mabi.Structs.Stat.`

I want to cry right now. I think I need to go back to bed. I apologize.

**Pull request closed without merging**
