### PR TITLE
Shutdown command

### PR DESCRIPTION
**Pull request by ImaBrokeDude**
An implementation attempt to satisfy #25

### CODE REVIEW

**Comment by QewQew** [comment]
You had to make an entirely new PR with all the same content because 

> .... Tabbing.... UUUUUUGH!

?

**Comment by ImaBrokeDude** [comment]
I closed the pull request mistakenly, I wish I could have reopened the last one.

**Comment by QewQew** [comment]
image

**Comment by ImaBrokeDude** [comment]
Yeah that's my fault. Sorry. Guess I missed that.

**Comment by ImaBrokeDude** [comment]
Okay I believe I have found all I could find, just need community review

**Comment by ImaBrokeDude** [comment]
Hi guys sorry about that because there is a preexisting pull request in progress, and the reason behind this one is not valid, I am going to clean this pull request. I am sorry to waste everyone's time! Please forgive me!

**Pull request closed without merging**
