### PR TITLE
Add Stewart PTJ

### PR DESCRIPTION
**Pull request by valdeza**
Note: Stewart does not have dialogue for speaking to him while on the job.

51 PTJs with small variations between them. I **had** to use that somewhat complex abstract class. D:

### Issue_ 
While still completable, progression with library PTJs is hindered with forced sequential objective completion and needing to trigger inventory update to acknowledge you collected a book. ( #230 )

_Resolved: Since the library is unavailable, shelving the books could not be tested. I **think** it works, though._

ref: #237

###### Sure the library is for the public, but the books are not for the public _to keep_. No one apparently returns books in Dunbarton!

_Edits_
1. Receive & shelve PTJs tested

### CODE REVIEW

**Comment by valdeza** [comment]
Also (forgot to mention), Stewart doesn't exactly have quest levels. Someone qualified for advanced will get the same set of quests as one who is working for him for the first time.

To suppress that "Missing quest for level 'Adv'" warning, should we 
set all of Stewart's PTJs to QuestLevel.None and check for that when selecting a random PTJ or 
write a some method NpcScript.RandomPtjIgnoreLevel(PtjType, params int[]) that skips all the level checks?

**Comment by exectails** [comment]
>To suppress that "Missing quest for level 'Adv'" warning

Actually, with this requirement change we could simply disable the warning. It's there because we were assuming same level PTJs being missing would be a bug, but if falling back to previous levels is an option if there are no higher ones, we don't need to warn anymore. It does what it's supposed to.

>I had to use that somewhat complex abstract class.

Technically you didn't *have* to* =P

>Since the library is unavailable, shelving the books could not be tested. I think it works, though.

It might have, but aside from the library warp not working, the bookshelf NPCs were also missing xD" Just added them, you can now test everything. Since it looks like they do nothing but End the dialog with a message right away by default, I gave them an `after_intro` hook, even though they don't really have an intro, and a call to End. If you hook them you should probably end the dialog from the hook, otherwise the script would continue to the End message.

**Comment by xCryptic** [comment]
I didn't even know those bookshelves were g1 o_o

**Comment by exectails** [comment]
Hm. Hard to say =/ The library dungeon is not G1, but did the library itself exist? If so, it's likely that the shelves existed as well, otherwise the region would've been empty.

**Comment by exectails** [comment]
2000 lines, *with* heavy abstraction... and I was already annoyed by Endelyon's PTJ^^" Thanks for your hard work.

**Pull request merged**
