### PR TITLE
Sitting on props

### PR DESCRIPTION
**Pull request by DennouNeko**
Making the Rest skill search for and use nearby sittable props.

### CODE REVIEW

**Comment by exectails** [comment]
Thanks for the contribution, I've been meaning to look into this^^

**Comment by DennouNeko** [comment]
No problem.
I was running around later on, checking the props I know, and seems like later on the range may be increased just a bit. For example, that sofa at Manus' has 3 spots to seat on, but so far got only the middle one to work...

**Comment by exectails** [comment]
Maybe there's more than one variable? I guess there would have to be, because the prop needs to know who sits where, and which spots are taken.

**Comment by DennouNeko** [comment]
Doesn't seem like it... From what I've seen in area file, all 3 spots are added as separate props.

**Comment by exectails** [comment]
Oh. So lazy =<

**Pull request merged**
