### PR TITLE
Corrects documentation for SetAccountPassword

### PR DESCRIPTION
**Pull request by ImaBrokeDude**
* Corrects doc for `Aura.Shared.AuraDb.SetAccountPassword(...)`

### CODE REVIEW

**Comment by Cosrnos** [comment]
Just a preference, when making commits can you be a bit more specific? For example:

```
Corrects documentation for SetAccountPassword
```

reads a lot better than

```
Document Correction
```

**Comment by ImaBrokeDude** [comment]
Updated, sorry about that!

**Comment by Cosrnos** [comment]
@ImaBrokeDude No worries! And just for reference I was talking about the actual commit message (bd19abbaeabe556d78a172b4474e9cf1e74bc35a)

**Comment by ImaBrokeDude** [comment]
@Cosrnos  Ah yeah, I actually was going to put that... and then changed my mind... I will trust my instinct on that matter more next time.

**Pull request merged**
