### PR TITLE
Use client data to calculate weather tables

### PR DESCRIPTION
**Pull request by Tachiorz**

### CODE REVIEW

**Comment by exectails** [comment]
Something is wrong, the rain strength in `WeatherDetails` is incorrect.

**Comment by Tachiorz** [comment]
Remove weathercommon.mpk from cache. Weather table will differ every 625 steps, this is intentional. Flaw in original random generator.

**Comment by exectails** [comment]
I guess I was lucky to find that problem then o.o Downloaded your branch, logged in, got wrong values^^ So the one that differs is always completely random? Because it reads out of bounds?

**Comment by Tachiorz** [comment]
Yeah, one that differ should be completely random every run. I sent you privately sources, there is a loop that tests original and reversed random generators side by side. You can look at it and make sure that it's different every run.

**Comment by Tachiorz** [comment]
Added "Unknown" weather. It's encoded as -1.0f in weathercommon.mpk, old file should be removed from cache

**Comment by exectails** [comment]
Looks good, I'll merge it after a last test tomorrow. GJ.

**Pull request merged**
