### PR TITLE
Added Password Changing

### PR DESCRIPTION
**Pull request by xeroplz**
Decided to do this since I got irritated at making new accounts for
people who forgot their passwords :+1:

### CODE REVIEW

**Comment by exectails** [comment]
Please configure your IDE to use tabs instead of spaces and reformat the changed files.

**Comment by xeroplz** [comment]
"Please configure your IDE to use tabs instead of spaces and reformat the changed files."
um.... not 100% sure how 2 do

**Comment by Pikachews** [comment]
Take a look in the preferences. Or  at the least, Google.

**Comment by xeroplz** [comment]
Yep i found out how to do it... Now in order to reformat them... do I literally have to type it all in again?
:o

**Comment by Pikachews** [comment]
Reformat document

**Pull request closed without merging**
