### PR TITLE
Added NPC Pero

### PR DESCRIPTION
**Pull request by xCryptic**
We forgot about this guy )':

Thanks to @xKamuna for translating his 3rd greeting message :)

### CODE REVIEW

**Comment by exectails** [comment]
We forgot a G3 NPC? Oh noes~ =P

**Comment by xCryptic** [comment]
Oh.. he is? I don't remember what stuff came in which generations. Does
that mean goro is g3 too?
>
>

**Comment by xCryptic** [comment]
My bad, I forgot about adding him to the load list.

**Comment by exectails** [comment]
Good question, dunno about Goro. But Pero is in the DK and Paladin arena, that couldn't have been G1 content^^

**Comment by exectails** [comment]
You may want to start using `L`, so we have less to update later on.

**Comment by xCryptic** [comment]
@exectails Yeah, I just hate it when some lines are, some aren't. If I'm gonna do it, I'm doing it *all*. Of course, I'm not going to change anything back that has already been changed.

Btw, wasn't there someone updating everything with `L`'s? I would do it, but it's pretty low on my priorities.

**Comment by exectails** [comment]
There was, but he's taking a break. And you're saying you don't like one line L, one line not, but this was an entirely new NPC =P

**Comment by xCryptic** [comment]
Well technically it was a copy&paste from Goro.
>
>

**Pull request merged**
